name: Action Linting Workflow
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  github_action_linting:
    runs-on: ubuntu-latest
    name: github_action_linting
    steps:
      - name: Code Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Action Linting
        uses: cfy9/action-linting@main
        with:
          files: ".github/workflows/main.yaml"
          
      - name: Generate Semantic Version
        id: tag_version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main,master
          dry_run: false
          create_annotated_tag: true
